---
title: "run FinOMOP"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{run}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
devtools::load_all(".")
```

```{r}

base_path <- r"(C:\Users\javier\REPOS\GITHUB_FINNGEN\FinOMOP_OMOP_vocabulary)"

path_to_input_mapping_vocabularies_info_file <- file.path(base_path, "VOCABULARIES", "vocabularies_info.csv")
path_to_input_omop_vocabulary_folder <- file.path(base_path, "OMOP_VOCABULARIES", "input_omop_vocabulary")
path_to_input_database_counts_file <- file.path(base_path, "CODE_COUNTS", "databases_coverage.csv")
path_to_input_vocabularies_coverage_file <- file.path(base_path, "CODE_COUNTS", "vocabularies_coverage.csv")

path_to_temp_omop_vocabulary_folder <- file.path(base_path, "OMOP_VOCABULARIES", "temp_omop_vocabulary")

path_to_output_omop_vocabulary_folder <- file.path(base_path, "OMOP_VOCABULARIES", "output_omop_vocabulary")
path_to_output_dashboard_file <- file.path(base_path, "StatusReport", "dashboard.html")
```



# Read vocabularies_info.csv 

vocabularies_info.csv contains the information to build the vocabularies 

```{r}
mapping_tables <- importMappingTables(path_to_input_mapping_vocabularies_info_file)

usagi_mapping_tables <- mapping_tables$usagi_mapping_tables
vocabulary_info_mapping_tables <- mapping_tables$vocabulary_info_mapping_tables

usagi_mapping_tables
vocabulary_info_mapping_tables
```


temp fix:icd9fi, 
```{r}
usagi_mapping_tables[[4,5]][[1]] <- usagi_mapping_tables[[4,5]][[1]] |> 
dplyr::distinct(sourceCode, .keep_all = TRUE )
```


```{r}
usagi_mapping_tables <- usagi_mapping_tables |> validateTables("UsagiForCCR")
vocabulary_info_mapping_tables <- vocabulary_info_mapping_tables |> validateTables("VocabularyInfo")

usagi_mapping_tables |> filter(n_failed_rules!=0)
vocabulary_info_mapping_tables |> filter(n_failed_rules!=0)
```


# Convert mapping files to OMOP tables 

This will only run these with no errors
```{r}
convertMappingsTablesToOMOPtables(
  usagi_mapping_tables,
  vocabulary_info_mapping_tables,
  path_to_temp_omop_vocabulary_folder, 
  ignore_failed_rules = FALSE
)
```


# merge with ahtena vocabularies 

```{r}
mergeOMOPtables(path_to_input_omop_vocabulary_folder,
                path_to_temp_omop_vocabulary_folder,
                path_to_output_omop_vocabulary_folder)
```



## Validate the newely created vocabularies
```{r}
omop_tables <- importOMOPtables(path_to_output_omop_vocabulary_folder, c("CONCEPT","VOCABULARY", "CONCEPT_CLASS", "CONCEPT_RELATIONSHIP", "CONCEPT_SYNONYM"))

omop_tables <- validateTables(omop_tables)
omop_tables <- validateOMOPTablesRelationships(omop_tables)

omop_tables
```


## Import code counts

```{r}
databases_code_counts_tables <- importDatabasesCodeCountsTables(path_to_input_database_counts_file)

databases_code_counts_tables <- validateTables(databases_code_counts_tables, table_type = "CodeCounts")

databases_code_counts_tables

```

autofix
```{r}

databases_code_counts_tables <- databases_code_counts_tables |> 
  mutate(table = if_else(n_failed_rules==0, table, 
                                map2(.x=table, .y=name, .f=~autoFixDatabaseCodeCountTable(.x,.y))
                                ))

databases_code_counts_tables <- validateTables(databases_code_counts_tables, table_type = "CodeCounts")

databases_code_counts_tables

```



# check coverage 

```{r}
mapping_status <- calculateMappingStatus(
  path_to_input_vocabularies_coverage_file,
  omop_tables, 
  databases_code_counts_tables)
```


```{r}
plotTableMappingStatus(mapping_status)
```

```{r}
plotTableVocabularyStatus(mapping_status, "ICD10fi")
```

# Build report

```{r}
tmp_html <- path_to_output_dashboard_file
buildStatusDashboard(
  usagi_mapping_tables = usagi_mapping_tables,
  vocabulary_info_mapping_tables = vocabulary_info_mapping_tables,
  omop_tables  = omop_tables, 
  databases_code_counts_tables = databases_code_counts_tables, 
  mapping_status  = mapping_status,
  output_file_html = tmp_html)
browseURL(tmp_html) 
```






# Test dqd against sqlite 

```{r}

sql <- SqlRender::readSql(system.file("ddl/5.4/sql_server/OMOPCDM_sql_server_5.4_ddl.sql", package = "CommonDataModel", mustWork = TRUE))
sql <- SqlRender::render(
    sql = sql,
    cdmDatabaseSchema = "main"
    )
sql <- SqlRender::translate(
    sql = sql,
    targetDialect = "duckdb"
  )


databaseFile <- tempfile()
cd <- DatabaseConnector::createConnectionDetails(
  dbms = "duckdb", 
  server = databaseFile, 
  pathToDriver = "../../"
)

c <- DatabaseConnector::connect(cd)

DatabaseConnector::dbExecute(c, sql)

vocab_table_names <- c(
  "CONCEPT", 
  "CONCEPT_ANCESTOR", 
  "CONCEPT_CLASS", 
  "CONCEPT_RELATIONSHIP",
  "CONCEPT_SYNONYM",
  "DOMAIN",
  "RELATIONSHIP",
  "VOCABULARY"
)


for(vocab_table_name in vocab_table_names){
  
  print(vocab_table_name)
  
  p <- file.path(path_to_output_omop_vocabulary_folder, paste0(vocab_table_name,".csv"))
  DatabaseConnector::dbExecute(c, paste0("COPY ", vocab_table_name," FROM '",p,"' (DATEFORMAT '%Y%m%d', DELIM '\t', HEADER true, QUOTE '')"))

}

DatabaseConnector::dbExecute(c, "INSERT INTO main.cdm_source VALUES ('test', 'test', 'test', 'test', 'test', 'test', DATE '1992-09-20' , DATE '1992-09-20', 'test', 1, 'test')")

DatabaseConnector::disconnect(c)
```


```{r}

tablesToExclude = c(
"CARE_SITE",  "COHORT", "COHORT_ATTRIBUTE",  
 "CONDITION_ERA"  ,     
"CONDITION_OCCURRENCE", "COST", "DEATH", "DEVICE_EXPOSURE",            
"DOSE_ERA", "DRUG_ERA", "DRUG_EXPOSURE",  "FACT_RELATIONSHIP",    
"LOCATION", "MEASUREMENT", "METADATA", "NOTE", "NOTE_NLP" ,           
"OBSERVATION", "OBSERVATION_PERIOD", "PAYER_PLAN_PERIOD",  "PROCEDURE_OCCURRENCE" ,
"PROVIDER",   "SPECIMEN", "VISIT_DETAIL"         ,
"VISIT_OCCURRENCE" , "EPISODE", "EPISODE_EVENT", "PERSON" , "CDM_SOURCE", "COHORT_DEFINITION" )

a <- DataQualityDashboard::executeDqChecks(connectionDetails = cd, 
                                    cdmDatabaseSchema = "main", 
                                    resultsDatabaseSchema = "main", 
                                    cdmSourceName = "test", 
                                    outputFolder = tempdir(), 
                                    tablesToExclude = tablesToExclude, cdmVersion = "5.4"
                                    
                                    )
                                    


```



