---
title: "Mapping status FinOMOP"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params: 
  usagi_mapping_tables: NULL
  vocabulary_info_mapping_tables: NULL
  results_DQD: NULL
  databases_code_counts_tables: NULL
  mapping_status: NULL
---


```{r}
library(flexdashboard)
```

```{r}
usagi_mapping_tables <- params$usagi_mapping_tables
vocabulary_info_mapping_tables <- params$vocabulary_info_mapping_tables
results_DQD <- params$results_DQD
databases_code_counts_tables <- params$databases_code_counts_tables
mapping_status <- params$mapping_status
```


Databases Coverage
=====================================


Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------
### Description

This table summarizes the current status of the FimOMOP mapping repository.

Each row shows a `Vocabulary`. If it is `Maintaned by` OMOP, FinnOMOP, or OMOP+FinnOMOP for a combination of both.
`Mapping progress` shows the proportion of codes in a vocabulary that have been mapped to one or more OMOP-standard concepts.


Following columns, shows how well the vocabulary covers the events in different databases. Last column is a combination of all the databases.
A code used in a clinical event may fall in one of the following categories:


<span style="background-color: #51A350">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> **Events with standard code**: the code exist in the target vocabulary and is mapped to an OMOP-standard concept.

<span style="background-color: #F1AE4A">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> **Events with non-standard code**: the code exist in the target vocabulary but is not yet mapped to an OMOP-standard concept

<span style="background-color: #EC6173">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> **Events with not found code**: the code do not exist in the target vocabulary.


Exactly what events fall in each category can be explored by selecting the vocabulary's tab over the main table.

Hover over the bars to see details.



Column {.tabset}
-----------------------------------------------------------------------

### Summary

```{r}
if(!is.null(mapping_status)){
  plotTableMappingStatus(mapping_status)
}

```

```{r results='asis'}
if(!is.null(mapping_status)){
  
  valid_source_vocabulary_id <- mapping_status$code_counts_matched |>
    dplyr::distinct(source_vocabulary_id) |>
    dplyr::pull(source_vocabulary_id)
  
  for(source_vocabulary_id in valid_source_vocabulary_id){
    
    cat("### ", source_vocabulary_id, "\n")
    
    shiny::div(
      tryCatch({
        plotTableVocabularyStatus(mapping_status, source_vocabulary_id)
      }, error = function(e) {
        if(stringr::str_detect(e$message, "Each row of output must be identified")){
          return("ERROR, THE VOCABULARY HAS DUPLICATED SOURCE CODES !!!")
        }else{
          return(e$message)
        }
      } )
    ) |>
      print()
  }
  
}
```



OMOP Tables Validation
=====================================

Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------
### Description

This table shows the results from the DataQualityDashboard applied to the OMOP vocabulary tables. 
It checks that the modified OMOP vocabulary tables maintain the conformance and plausibility rules defined by the CDM definitions.  


Column {.tabset}
-----------------------------------------------------------------------

### Summary
```{r }
if(!is.null(results_DQD)){
  results_DQD$CheckResults |>  tibble::as_tibble() |> 
    dplyr::transmute(
      Status = dplyr::case_when(
        isError==1 ~ "ERROR", 
        failed==1 ~ "FAIL",
        passed==1 ~ "PASS"
      ), 
      Table=cdmTableName, 
      Field=cdmFieldName, 
      Category=category, 
      Subcategory=subcategory, 
      Description=checkDescription, 
      `% Records` = pctViolatedRows
    ) |> 
    reactable::reactable(
      resizable = TRUE,
      filterable = TRUE,
      defaultPageSize = 20
    )
  
}
```



USAGI Tables Validation
===================================== 

Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------
### Description 
This table shows the quality checks done in the usagi mapping files. 
This helps to the source of a possible error in the "OMOP Tables Validation"

The Summary tab shows a summary of the input vocabularies and if they have any failed rules, `n_failed_rules` column. 

Additionally, there is one tab per vocabulary showing the list of checks (Validation Summary) and the specific rows causing the error if any (Failed Rules).


Column {.tabset}
-----------------------------------------------------------------------

### Summary
```{r }
if(!is.null(usagi_mapping_tables)){
  .printSumary(usagi_mapping_tables)
}
```

```{r results='asis'}
if(!is.null(usagi_mapping_tables)){
  .printValidationTables(usagi_mapping_tables)
}
```


Vocabulary Info Tables Validation
===================================== 

Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------
### Description 
This table shows the quality checks done in the info mapping files. 
This helps to the source of a possible error in the "OMOP Tables Validation"

The Summary tab shows a summary of the input vocabularies and if they have any failed rules, `n_failed_rules` column. 

Additionally, there is one tab per vocabulary showing the list of checks (Validation Summary) and the specific rows causing the error if any (Failed Rules).


Column {.tabset}
-----------------------------------------------------------------------

### Summary
```{r }
if(!is.null(vocabulary_info_mapping_tables)){
  .printSumary(vocabulary_info_mapping_tables)
}
```

```{r results='asis'}
if(!is.null(vocabulary_info_mapping_tables)){
  .printValidationTables(vocabulary_info_mapping_tables)
}
```



Databases Counts Tables Validation
=====================================

Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------
### Description 
This table shows the quality checks done in the code_counts files. 

The Summary tab shows a summary of the input databases and if they have any failed rules, `n_failed_rules` column. 

Additionally, there is one tab per database showing the list of checks (Validation Summary) and the specific rows causing the error if any (Failed Rules).

Column {.tabset}
-----------------------------------------------------------------------

### Summary
```{r }
if(!is.null(databases_code_counts_tables)){
  .printSumary(databases_code_counts_tables)
}
```

```{r results='asis'}
if(!is.null(databases_code_counts_tables)){
  .printValidationTables(databases_code_counts_tables)
}
```












