---
title: "Coverage of Vocabulary in Database"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params: 
  summaryTableForVocabularyAndDatabase: NULL
  sourceVocabularyId: NULL
  databaseName: NULL
---


```{r}
library(flexdashboard)

summaryTableForVocabularyAndDatabase <- params$summaryTableForVocabularyAndDatabase
sourceVocabularyId <- params$sourceVocabularyId
databaseName <- params$databaseName

# Update tab title
title <- paste0(sourceVocabularyId, " in ", databaseName)
htmltools::tags$script(paste0("document.title = '", title, "';"))
```

```{r, results='asis'}
# Update Dashboar title
cat(paste0("# ", sourceVocabularyId, " in ", databaseName, "\n"))
```


Column {.tabset}
-----------------------------------------------------------------------
### Mappings

```{r}
colors <- list(
  invalid = "#EC6173",
  unmapped = "#F1AE4A",
  mapsTo = "#51A350",
  grey = "#AAAAAA"
)

.plotTableForVocabularyAndDatabase(summaryTableForVocabularyAndDatabase, colors)
```

### Summary

```{r}
.plotSummaryTableForVocabularyAndDatabase(summaryTableForVocabularyAndDatabase, colors)
```
 